name: Build and Push to ECR

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/docker-build-push.yaml'
    branches:
      - payaza-test
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Change this to your AWS region

      - name: Build and push Docker image
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login -u AWS --password-stdin ${{ secrets.AWS_REGISTRY_URL }}
          docker build -t ${{ secrets.AWS_REGISTRY_URL }}/payaza-devops-assessment:latest ./app
          docker push ${{ secrets.AWS_REGISTRY_URL }}/payaza-devops-assessment:latest

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster payaza-test-cluster --service simple-api-service --force-new-deployment --region eu-west-2
