name: Terraform Apply

on:
  push:
    paths:
      - 'infrastructure/**'
    branches:
      - payaza-test

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up AWS credentials
        run: |
          echo "TF_VAR_aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "TF_VAR_aws_region=eu-west-2" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Cleanup
        run: rm -rf .terraform
