name: Terraform Apply

on:
  push:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/terraform-deployment.yaml'
    branches:
      - payaza-test

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          cd infrastructure
          terraform init
          cd ..

      - name: Validate Terraform
        run: |
          cd infrastructure
          terraform validate
          cd ..

      - name: Plan Terraform Changes
        run: |
          cd infrastructure
          terraform plan
          cd ..

      - name: Apply Terraform Changes
        run: |
          cd infrastructure
          terraform apply -auto-approve
        env:
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: "eu-west-2"  # Change this to your AWS region

      - name: Cleanup
        run: |
          cd infrastructure
          rm -rf .terraform
          cd ..
